/// ============================================================
/// DIMENSIÓN: dim_territorio
/// Fuente: MongoDB Atlas SQL → northwind_dw.dim_territorio
/// Responde: P6 (análisis territorial), P7 (entrega por región)
/// ============================================================
table dim_territorio
	lineageTag: 846a60c1-c02e-415a-984c-a992b2d9edc5

	column territorio_id
		dataType: string
		isKey
		displayFolder: Claves
		lineageTag: c8a4dbf5-f83c-4146-b92f-80d4dd63dc8b
		summarizeBy: none
		sourceColumn: territorio_id

	column country
		dataType: string
		lineageTag: b16dc744-8009-48af-94d2-3a4ae9d5bf90
		dataCategory: Country
		summarizeBy: none
		sourceColumn: country

	column region
		dataType: string
		lineageTag: bdf98dff-09a3-4f18-847a-cc9e4faa1dee
		summarizeBy: none
		sourceColumn: region

	column continente
		dataType: string
		lineageTag: 50e92057-fd7b-4cba-a082-6217f42451bf
		summarizeBy: none
		sourceColumn: continente

	column zona
		dataType: string
		lineageTag: 95f795f2-ac36-4cbc-95d6-9edaf98e014d
		summarizeBy: none
		sourceColumn: zona

	column _id
		dataType: string
		lineageTag: df918077-0503-4f29-848c-649fae317d37
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: e2f938c3-b686-46f4-af22-c860009994c4
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	hierarchy 'Jerarquía Territorial'
		lineageTag: 2aae7728-2f02-40e8-8b30-a02be4e7b051

		level Continente
			lineageTag: e8fb9b42-b0b5-46e8-8fb3-2402c3a47897
			column: continente

		level Zona
			lineageTag: 9c24c3f0-a5e9-4e1f-9087-7ed29cd6402f
			column: zona

		level País
			lineageTag: b2c0ae76-d064-423e-a68d-6771adb73611
			column: country

	partition dim_territorio-m = m
		mode: import
		source =
				let
				  Origen = MongoDBAtlasODBC.Contents("mongodb://atlas-sql-6930c29c08aae91552e44bdc-8l1q1z.a.query.mongodb.net/northwind_dw?ssl=true&authSource=admin", "northwind_dw", []),
				  #"Navegación 1" = Origen{[Name = "northwind_dw", Kind = "Database"]}[Data],
				  #"Navegación 2" = #"Navegación 1"{[Name = "dim_territorio", Kind = "Table"]}[Data],
				  #"Tipo cambiado" = Table.TransformColumnTypes(#"Navegación 2", {
				    {"territorio_id", type text}, {"country", type text}, {"region", type text},
				    {"continente", type text}, {"zona", type text}, {"_id", type text}, {"city", type text}
				  })
				in
				  #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

