/// ============================================================
/// DIMENSIÓN: dim_empleado
/// Fuente: MongoDB Atlas SQL → northwind_dw.dim_empleado (9 registros)
/// Responde: P5 (eficiencia vendedores), P6 (territorios)
/// ============================================================
table dim_empleado
	lineageTag: 2af8621c-953f-4647-a86a-4aae20049590

	column empleado_id
		dataType: int64
		isKey
		displayFolder: Claves
		lineageTag: 73f600b4-7bf2-4fe0-b2a3-81b67e722b59
		summarizeBy: none
		sourceColumn: empleado_id

	column last_name
		dataType: string
		isHidden
		lineageTag: 9362ea32-b66a-4904-9be8-cdeb87af65ff
		summarizeBy: none
		sourceColumn: last_name

	column first_name
		dataType: string
		isHidden
		lineageTag: f034c406-ce3f-44da-bf8e-be6135ef5b66
		summarizeBy: none
		sourceColumn: first_name

	column full_name
		dataType: string
		lineageTag: 93468203-cc42-4560-a571-ab9911695918
		summarizeBy: none
		sourceColumn: full_name

	column title
		dataType: string
		lineageTag: 66f85483-4ea0-4c88-8f90-13ab925ec598
		summarizeBy: none
		sourceColumn: title

	column hire_date
		dataType: dateTime
		isHidden
		formatString: dd/MM/yyyy
		lineageTag: 665dab99-9da1-40bf-9412-f8990711a61e
		summarizeBy: none
		sourceColumn: hire_date

	column city
		dataType: string
		lineageTag: 63e05174-0c22-46b4-92b8-2fb5399062b5
		summarizeBy: none
		sourceColumn: city

	column region
		dataType: string
		lineageTag: e2efea4b-0eef-4dff-bd94-5882475dd377
		summarizeBy: none
		sourceColumn: region

	column country
		dataType: string
		lineageTag: a249ff79-e152-4be3-b9c1-23ced77fbe3a
		summarizeBy: none
		sourceColumn: country

	column reports_to
		dataType: int64
		isHidden
		lineageTag: cef6f25d-6e20-4a5f-9032-19714436540d
		summarizeBy: none
		sourceColumn: reports_to

	column _id
		dataType: string
		lineageTag: 0eb9af8e-95c4-4fae-94b9-fb3d02903bda
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	partition dim_empleado-m = m
		mode: import
		source =
				let
				  Origen = MongoDBAtlasODBC.Contents("mongodb://atlas-sql-6930c29c08aae91552e44bdc-8l1q1z.a.query.mongodb.net/northwind_dw?ssl=true&authSource=admin", "northwind_dw", []),
				  #"Navegación 1" = Origen{[Name = "northwind_dw", Kind = "Database"]}[Data],
				  #"Navegación 2" = #"Navegación 1"{[Name = "dim_empleado", Kind = "Table"]}[Data],
				  #"Tipo cambiado" = Table.TransformColumnTypes(#"Navegación 2", {
				    {"empleado_id", Int64.Type}, {"last_name", type text}, {"first_name", type text},
				    {"full_name", type text}, {"title", type text}, {"hire_date", type datetime},
				    {"city", type text}, {"region", type text}, {"country", type text},
				    {"reports_to", Int64.Type}, {"_id", type text}
				  })
				in
				  #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

