/// ============================================================
/// DIMENSIÓN: dim_cliente
/// Fuente: MongoDB Atlas SQL → northwind_dw.dim_cliente (91 registros, 21 países)
/// Responde: P2 (clientes rentables), P6 (geografía), P9 (inactivos)
/// ============================================================
table dim_cliente
	lineageTag: 37507262-757a-47b4-b8cf-18f6e1ba6356

	column cliente_id
		dataType: string
		isKey
		displayFolder: Claves
		lineageTag: 462dacca-7dbf-4658-aa7b-3cc8693b2ecf
		summarizeBy: none
		sourceColumn: cliente_id

	column company_name
		dataType: string
		lineageTag: 800d68c3-5cdf-465e-8ae0-a271fb366a0f
		summarizeBy: none
		sourceColumn: company_name

	column contact_name
		dataType: string
		isHidden
		lineageTag: 4b2f72a2-66e1-41ed-946b-997551adda28
		summarizeBy: none
		sourceColumn: contact_name

	column contact_title
		dataType: string
		isHidden
		lineageTag: 1c4d159d-718f-493f-896d-88493f36b7af
		summarizeBy: none
		sourceColumn: contact_title

	column city
		dataType: string
		lineageTag: 609b37b5-d0e9-436f-89aa-fefa6c242242
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

	column region
		dataType: string
		lineageTag: ce97aecb-3210-4235-ae1e-b833244a219c
		summarizeBy: none
		sourceColumn: region

	column country
		dataType: string
		lineageTag: 564dc484-5c5b-4f7c-812d-8de469b0d8a5
		dataCategory: Country
		summarizeBy: none
		sourceColumn: country

	column address
		dataType: string
		isHidden
		lineageTag: 3184c493-372c-4bce-9b45-eed7314143fd
		summarizeBy: none
		sourceColumn: address

	column postal_code
		dataType: string
		isHidden
		lineageTag: a33bee43-9d18-43a4-8390-ee9a7b9f6119
		summarizeBy: none
		sourceColumn: postal_code

	column phone
		dataType: string
		isHidden
		lineageTag: 331d424f-290f-42c6-8696-fa01d9d48b7a
		summarizeBy: none
		sourceColumn: phone

	column fax
		dataType: string
		isHidden
		lineageTag: 4c5cd1fb-fd2c-4976-bfe9-ce057dd796ce
		summarizeBy: none
		sourceColumn: fax

	column _id
		dataType: string
		lineageTag: 3c8edfc9-3a81-4f75-8001-cdf3a6f52b67
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column n_ordenes
		dataType: int64
		formatString: 0
		lineageTag: 2da9ca4e-3e08-4f29-9908-a7dabfb22964
		summarizeBy: none
		sourceColumn: n_ordenes

		annotation SummarizationSetBy = Automatic

	column segmento_cliente
		dataType: string
		lineageTag: 63fdf8da-ef88-4aa3-9690-c02b87f67a33
		summarizeBy: none
		sourceColumn: segmento_cliente

		annotation SummarizationSetBy = Automatic

	column total_ventas_usd
		dataType: double
		lineageTag: 284e77b9-1eb3-45af-8c16-3bfab04b1c0e
		summarizeBy: none
		sourceColumn: total_ventas_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy 'Jerarquía Geográfica Cliente'
		lineageTag: 4f70b033-64a0-49a4-a9fd-e39f5c9692a2

		level País
			lineageTag: 4f14a207-fd68-4e4c-b640-dfed12916c7e
			column: country

		level Ciudad
			lineageTag: b0bd25b5-199c-48dc-ab5c-d7ba9cc8f650
			column: city

		level Cliente
			lineageTag: 757ddb17-c5f4-4da8-aa4c-757f850e0a31
			column: company_name

	partition dim_cliente-m = m
		mode: import
		source =
				let
				  Origen = MongoDBAtlasODBC.Contents("mongodb://atlas-sql-6930c29c08aae91552e44bdc-8l1q1z.a.query.mongodb.net/northwind_dw?ssl=true&authSource=admin", "northwind_dw", []),
				  #"Navegación 1" = Origen{[Name = "northwind_dw", Kind = "Database"]}[Data],
				  #"Navegación 2" = #"Navegación 1"{[Name = "dim_cliente", Kind = "Table"]}[Data],
				  #"Tipo cambiado" = Table.TransformColumnTypes(#"Navegación 2", {
				    {"cliente_id", type text}, {"company_name", type text}, {"contact_name", type text},
				    {"contact_title", type text}, {"city", type text}, {"region", type text},
				    {"country", type text}, {"address", type text}, {"postal_code", type text},
				    {"phone", type text}, {"fax", type text}, {"_id", type text},
				    {"n_ordenes", Int64.Type}, {"segmento_cliente", type text}, {"total_ventas_usd", type number}
				  })
				in
				  #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

