/// ============================================================
/// DIMENSIÓN: dim_producto
/// Fuente: MongoDB Atlas SQL → northwind_dw.dim_producto (77 productos, 8 categorías)
/// Responde: P3 (más vendidos), P4 (por categoría), P8 (margen)
/// ============================================================
table dim_producto
	lineageTag: 02c1475f-3972-4e46-b533-49cd54d51f7b

	column producto_id
		dataType: int64
		isKey
		displayFolder: Claves
		lineageTag: 02338b41-a0bc-4124-bcbe-d86026ed40e1
		summarizeBy: none
		sourceColumn: producto_id

	column product_name
		dataType: string
		lineageTag: 2633fa41-f4f0-4803-bbd0-24cd6e63f6db
		summarizeBy: none
		sourceColumn: product_name

	column categoria_id
		dataType: int64
		isHidden
		displayFolder: Claves
		lineageTag: 20669bc3-82e2-47dd-94ca-d8b436bf568d
		summarizeBy: none
		sourceColumn: categoria_id

	column categoria
		dataType: string
		lineageTag: 2b64e804-112e-453f-88da-dc47ec82c824
		summarizeBy: none
		sourceColumn: categoria

	column proveedor_id
		dataType: int64
		isHidden
		lineageTag: 03a5de65-8866-408c-a98e-1feb5005716b
		summarizeBy: none
		sourceColumn: proveedor_id

	column unit_price
		dataType: double
		formatString: $#,##0.00
		lineageTag: e16263ea-e4e7-4cd0-9440-61deda3f5ba7
		summarizeBy: none
		sourceColumn: unit_price

	/// Estimado = 60% del UnitPrice histórico (supuesto documentado Fase 1)
	column costo_adquisicion
		dataType: double
		formatString: $#,##0.00
		lineageTag: 07563fc4-ab42-4e49-8c76-71bc4ece12d2
		summarizeBy: none
		sourceColumn: costo_adquisicion

	column units_in_stock
		dataType: int64
		lineageTag: 2508c8d6-9780-4695-aa0a-6bca6a5ea7bb
		summarizeBy: none
		sourceColumn: units_in_stock

	column units_on_order
		dataType: int64
		lineageTag: 1c62f984-03d5-414a-895d-49305596bf2a
		summarizeBy: none
		sourceColumn: units_on_order

	column reorder_level
		dataType: int64
		isHidden
		lineageTag: 6a0d2510-8f00-469e-bba8-35f9c63d1e86
		summarizeBy: none
		sourceColumn: reorder_level

	column discontinued
		dataType: boolean
		lineageTag: 149a5b71-b087-4f5e-83c0-45cbe791f9cb
		summarizeBy: none
		sourceColumn: discontinued

	column _id
		dataType: string
		lineageTag: bf974d6d-97f8-4d3e-9793-bfc43e028369
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column proveedor
		dataType: string
		lineageTag: b7d6e032-b886-4667-8146-872daf8a3fd1
		summarizeBy: none
		sourceColumn: proveedor

		annotation SummarizationSetBy = Automatic

	hierarchy 'Jerarquía Producto'
		lineageTag: 76c58772-c34e-438a-8f5d-865d608336d1

		level Categoría
			lineageTag: 552a964a-702a-462c-bf1a-8f4eed6fc2b0
			column: categoria

		level Producto
			lineageTag: f226da6f-06ad-4384-8b33-a279052c67e3
			column: product_name

	partition dim_producto-m = m
		mode: import
		source =
				let
				  Origen = MongoDBAtlasODBC.Contents("mongodb://atlas-sql-6930c29c08aae91552e44bdc-8l1q1z.a.query.mongodb.net/northwind_dw?ssl=true&authSource=admin", "northwind_dw", []),
				  #"Navegación 1" = Origen{[Name = "northwind_dw", Kind = "Database"]}[Data],
				  #"Navegación 2" = #"Navegación 1"{[Name = "dim_producto", Kind = "Table"]}[Data],
				  #"Tipo cambiado" = Table.TransformColumnTypes(#"Navegación 2", {
				    {"producto_id", Int64.Type}, {"product_name", type text}, {"categoria_id", Int64.Type},
				    {"categoria", type text}, {"proveedor_id", Int64.Type}, {"unit_price", type number},
				    {"costo_adquisicion", type number}, {"units_in_stock", Int64.Type},
				    {"units_on_order", Int64.Type}, {"reorder_level", Int64.Type},
				    {"discontinued", type logical}, {"_id", type text}, {"proveedor", type text}
				  })
				in
				  #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

