/// ============================================================
/// DIMENSIÓN: dim_shipper
/// Fuente: Northwind.Shippers (3 transportistas)
/// Responde: P7 (tiempos de entrega por transportista)
/// ============================================================
table dim_shipper
	lineageTag: 0d70e9bb-2e81-42c6-91bf-224940efa241

	column shipper_id
		dataType: int64
		isKey
		displayFolder: Claves
		lineageTag: 84aaecee-7d7e-4411-b8c8-146cfa7af0b2
		summarizeBy: none
		sourceColumn: shipper_id

	column company_name
		dataType: string
		lineageTag: abf0f72e-749c-4c68-8021-54f02885f708
		summarizeBy: none
		sourceColumn: company_name

	column phone
		dataType: string
		isHidden
		lineageTag: 81959110-f4b5-4d81-9e9a-f888e9221c27
		summarizeBy: none
		sourceColumn: phone

	column _id
		dataType: string
		lineageTag: 0b9ac52f-581d-4587-a3c9-78e48feb5507
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column avg_delivery_days
		dataType: double
		lineageTag: 1ebfdeff-0484-45b0-8cfe-eaa6df506d11
		summarizeBy: none
		sourceColumn: avg_delivery_days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_shipper-m = m
		mode: import
		source =
				let
				  Origen = MongoDBAtlasODBC.Contents("mongodb://atlas-sql-6930c29c08aae91552e44bdc-8l1q1z.a.query.mongodb.net/northwind_dw?ssl=true&authSource=admin", "northwind_dw", []),
				  #"Navegación 1" = Origen{[Name = "northwind_dw", Kind = "Database"]}[Data],
				  #"Navegación 2" = #"Navegación 1"{[Name = "dim_shipper", Kind = "Table"]}[Data],
				  #"Tipo cambiado" = Table.TransformColumnTypes(#"Navegación 2", {
				    {"shipper_id", Int64.Type}, {"company_name", type text}, {"phone", type text},
				    {"_id", type text}, {"avg_delivery_days", type number}
				  })
				in
				  #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

