model Model
	culture: es-CO
	defaultPowerBIDataSourceVersion: powerBI_V3
	sourceQueryCulture: en-US
	dataAccessOptions
		legacyRedirects
		returnErrorValuesAsNull

/// ============================================================
/// DIMENSIÓN: dim_fecha
/// Tabla calculada DAX — cubre el rango histórico Northwind
/// Responde: P1 (ventas por periodo), P10 (estacionalidad)
/// ============================================================
table dim_fecha
	isHidden

	partition 'dim_fecha-calc' = calculated
		mode: import
		source = ```
			VAR FechaBase =
			    CALENDAR( DATE(1996, 7, 4), DATE(1998, 5, 6) )
			RETURN
			    ADDCOLUMNS(
			        FechaBase,
			        "fecha_id",         FORMAT([Date], "YYYYMMDD"),
			        "anio",             YEAR([Date]),
			        "trimestre",        QUARTER([Date]),
			        "mes",              MONTH([Date]),
			        "nombre_mes",       FORMAT([Date], "MMMM"),
			        "semana_anio",      WEEKNUM([Date], 2),
			        "dia",              DAY([Date]),
			        "nombre_dia",       FORMAT([Date], "DDDD"),
			        "es_fin_semana",    IF(WEEKDAY([Date], 2) >= 6, TRUE(), FALSE())
			    )
			```

	column fecha_id
		dataType: string
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: fecha_id

	column fecha_completa
		dataType: dateTime
		formatString: "dd/MM/yyyy"
		summarizeBy: none
		sourceColumn: Date

	column anio
		dataType: int64
		summarizeBy: none
		sourceColumn: anio

	column trimestre
		dataType: int64
		summarizeBy: none
		sourceColumn: trimestre

	column mes
		dataType: int64
		summarizeBy: none
		sourceColumn: mes

	column nombre_mes
		dataType: string
		sortByColumn: mes
		summarizeBy: none
		sourceColumn: nombre_mes

	column semana_anio
		dataType: int64
		summarizeBy: none
		sourceColumn: semana_anio

	column dia
		dataType: int64
		summarizeBy: none
		sourceColumn: dia

	column nombre_dia
		dataType: string
		summarizeBy: none
		sourceColumn: nombre_dia

	column es_fin_semana
		dataType: boolean
		summarizeBy: none
		sourceColumn: es_fin_semana

	hierarchy 'Jerarquía Temporal'
		level Año
			column: anio
		level Trimestre
			column: trimestre
		level Mes
			column: nombre_mes
		level Día
			column: dia

/// ============================================================
/// DIMENSIÓN: dim_cliente
/// Fuente: Northwind.Customers (91 registros, 21 países)
/// Responde: P2 (clientes rentables), P6 (geografía), P9 (inactivos)
/// ============================================================
table dim_cliente

	partition 'dim_cliente-m' = m
		mode: import
		source = ```
			let
			    Source   = Sql.Database("(localdb)\\MSSQLLocalDB", "Northwind"),
			    Clientes = Source{[Schema="dbo", Item="Customers"]}[Data],
			    Sel = Table.SelectColumns(Clientes, {
			        "CustomerID", "CompanyName", "ContactName", "ContactTitle",
			        "Address", "City", "Region", "PostalCode", "Country",
			        "Phone", "Fax"
			    }),
			    Renamed = Table.RenameColumns(Sel, {
			        {"CustomerID",   "cliente_id"},
			        {"CompanyName",  "company_name"},
			        {"ContactName",  "contact_name"},
			        {"ContactTitle", "contact_title"},
			        {"Address",      "address"},
			        {"City",         "city"},
			        {"Region",       "region"},
			        {"PostalCode",   "postal_code"},
			        {"Country",      "country"},
			        {"Phone",        "phone"},
			        {"Fax",          "fax"}
			    })
			in
			    Renamed
			```

	column cliente_id
		dataType: string
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: cliente_id

	column company_name
		dataType: string
		summarizeBy: none
		sourceColumn: company_name

	column contact_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: contact_name

	column contact_title
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: contact_title

	column city
		dataType: string
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region

	column country
		dataType: string
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

	column address
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: address

	column postal_code
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: postal_code

	column phone
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: phone

	column fax
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: fax

	hierarchy 'Jerarquía Geográfica Cliente'
		level País
			column: country
		level Ciudad
			column: city
		level Cliente
			column: company_name

/// ============================================================
/// DIMENSIÓN: dim_empleado
/// Fuente: Northwind.Employees (9 registros)
/// Responde: P5 (eficiencia vendedores), P6 (territorios)
/// ============================================================
table dim_empleado

	partition 'dim_empleado-m' = m
		mode: import
		source = ```
			let
			    Source    = Sql.Database("(localdb)\\MSSQLLocalDB", "Northwind"),
			    Empleados = Source{[Schema="dbo", Item="Employees"]}[Data],
			    Sel = Table.SelectColumns(Empleados, {
			        "EmployeeID", "LastName", "FirstName", "Title",
			        "TitleOfCourtesy", "HireDate", "City", "Region",
			        "Country", "ReportsTo"
			    }),
			    Renamed = Table.RenameColumns(Sel, {
			        {"EmployeeID",       "empleado_id"},
			        {"LastName",         "last_name"},
			        {"FirstName",        "first_name"},
			        {"Title",            "title"},
			        {"TitleOfCourtesy",  "title_of_courtesy"},
			        {"HireDate",         "hire_date"},
			        {"City",             "city"},
			        {"Region",           "region"},
			        {"Country",          "country"},
			        {"ReportsTo",        "reports_to"}
			    }),
			    FullName = Table.AddColumn(Renamed, "full_name",
			        each [first_name] & " " & [last_name], type text)
			in
			    FullName
			```

	column empleado_id
		dataType: int64
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: empleado_id

	column last_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: last_name

	column first_name
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: first_name

	column full_name
		dataType: string
		summarizeBy: none
		sourceColumn: full_name

	column title
		dataType: string
		summarizeBy: none
		sourceColumn: title

	column title_of_courtesy
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: title_of_courtesy

	column hire_date
		dataType: dateTime
		formatString: "dd/MM/yyyy"
		isHidden
		summarizeBy: none
		sourceColumn: hire_date

	column city
		dataType: string
		summarizeBy: none
		sourceColumn: city

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region

	column country
		dataType: string
		summarizeBy: none
		sourceColumn: country

	column reports_to
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: reports_to

/// ============================================================
/// DIMENSIÓN: dim_producto
/// Fuente: Products + Categories (77 productos, 8 categorías)
/// Responde: P3 (más vendidos), P4 (por categoría), P8 (margen)
/// ============================================================
table dim_producto

	partition 'dim_producto-m' = m
		mode: import
		source = ```
			let
			    Source     = Sql.Database("(localdb)\\MSSQLLocalDB", "Northwind"),
			    Products   = Source{[Schema="dbo", Item="Products"]}[Data],
			    Categories = Source{[Schema="dbo", Item="Categories"]}[Data],
			    CatSel = Table.SelectColumns(Categories, {"CategoryID", "CategoryName"}),
			    Joined = Table.NestedJoin(
			        Products, "CategoryID",
			        CatSel,   "CategoryID",
			        "CatData", JoinKind.LeftOuter
			    ),
			    Expanded = Table.ExpandTableColumn(Joined, "CatData", {"CategoryName"}),
			    Sel = Table.SelectColumns(Expanded, {
			        "ProductID", "ProductName", "CategoryID", "CategoryName",
			        "SupplierID", "QuantityPerUnit", "UnitPrice",
			        "UnitsInStock", "UnitsOnOrder", "ReorderLevel", "Discontinued"
			    }),
			    CostoAdq = Table.AddColumn(Sel, "costo_adquisicion",
			        each [UnitPrice] * 0.60, type number),
			    Renamed = Table.RenameColumns(CostoAdq, {
			        {"ProductID",       "producto_id"},
			        {"ProductName",     "product_name"},
			        {"CategoryID",      "categoria_id"},
			        {"CategoryName",    "categoria"},
			        {"SupplierID",      "proveedor_id"},
			        {"QuantityPerUnit", "quantity_per_unit"},
			        {"UnitPrice",       "unit_price"},
			        {"UnitsInStock",    "units_in_stock"},
			        {"UnitsOnOrder",    "units_on_order"},
			        {"ReorderLevel",    "reorder_level"},
			        {"Discontinued",    "discontinued"}
			    })
			in
			    Renamed
			```

	column producto_id
		dataType: int64
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: producto_id

	column product_name
		dataType: string
		summarizeBy: none
		sourceColumn: product_name

	column categoria_id
		dataType: int64
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: categoria_id

	column categoria
		dataType: string
		summarizeBy: none
		sourceColumn: categoria

	column proveedor_id
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: proveedor_id

	column quantity_per_unit
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: quantity_per_unit

	column unit_price
		dataType: double
		formatString: "$#,##0.00"
		summarizeBy: none
		sourceColumn: unit_price

	/// Estimado = 60% del UnitPrice histórico (supuesto documentado Fase 1)
	column costo_adquisicion
		dataType: double
		formatString: "$#,##0.00"
		summarizeBy: none
		sourceColumn: costo_adquisicion

	column units_in_stock
		dataType: int64
		summarizeBy: none
		sourceColumn: units_in_stock

	column units_on_order
		dataType: int64
		summarizeBy: none
		sourceColumn: units_on_order

	column reorder_level
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: reorder_level

	column discontinued
		dataType: boolean
		summarizeBy: none
		sourceColumn: discontinued

	hierarchy 'Jerarquía Producto'
		level Categoría
			column: categoria
		level Producto
			column: product_name

/// ============================================================
/// DIMENSIÓN: dim_shipper
/// Fuente: Northwind.Shippers (3 transportistas)
/// Responde: P7 (tiempos de entrega por transportista)
/// ============================================================
table dim_shipper

	partition 'dim_shipper-m' = m
		mode: import
		source = ```
			let
			    Source   = Sql.Database("(localdb)\\MSSQLLocalDB", "Northwind"),
			    Shippers = Source{[Schema="dbo", Item="Shippers"]}[Data],
			    Renamed  = Table.RenameColumns(Shippers, {
			        {"ShipperID",   "shipper_id"},
			        {"CompanyName", "company_name"},
			        {"Phone",       "phone"}
			    })
			in
			    Renamed
			```

	column shipper_id
		dataType: int64
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: shipper_id

	column company_name
		dataType: string
		summarizeBy: none
		sourceColumn: company_name

	column phone
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: phone

/// ============================================================
/// DIMENSIÓN: dim_territorio
/// Fuente: ShipCountry único de Orders + mapa de zonas
/// Responde: P6 (análisis territorial), P7 (entrega por región)
/// ============================================================
table dim_territorio

	partition 'dim_territorio-m' = m
		mode: import
		source = ```
			let
			    Source  = Sql.Database("(localdb)\\MSSQLLocalDB", "Northwind"),
			    Orders  = Source{[Schema="dbo", Item="Orders"]}[Data],
			    Sel     = Table.SelectColumns(Orders, {"ShipCountry", "ShipRegion"}),
			    Unique  = Table.Distinct(Sel),
			    WithId  = Table.AddColumn(Unique, "territorio_id",
			        each Text.Upper(Text.Start([ShipCountry], 3)) & "-" &
			             Text.Upper(Text.Start(
			                 if [ShipRegion] = null then "XX" else [ShipRegion],
			                 2)),
			        type text),
			    WithZone = Table.AddColumn(WithId, "zona", each "Ver dashboard", type text),
			    WithCont = Table.AddColumn(WithZone, "continente", each "Ver dashboard", type text),
			    Renamed = Table.RenameColumns(WithCont, {
			        {"ShipCountry", "country"},
			        {"ShipRegion",  "region"}
			    })
			in
			    Renamed
			```

	column territorio_id
		dataType: string
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: territorio_id

	column country
		dataType: string
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region

	column continente
		dataType: string
		summarizeBy: none
		sourceColumn: continente

	column zona
		dataType: string
		summarizeBy: none
		sourceColumn: zona

	hierarchy 'Jerarquía Territorial'
		level Continente
			column: continente
		level Zona
			column: zona
		level País
			column: country

/// ============================================================
/// DIMENSIÓN: dim_metas_empleado
/// Tabla calculada DAX — metas de ventas trimestrales por cargo
/// Responde: P5 (eficiencia vs. metas)
/// ============================================================
table dim_metas_empleado
	isHidden

	partition 'dim_metas_empleado-calc' = calculated
		mode: import
		source = ```
			SELECTCOLUMNS(
			    GENERATE(
			        GENERATE(
			            DATATABLE(
			                "empleado_id", INTEGER,
			                "title",       STRING,
			                {
			                    {1, "Sales Representative"},
			                    {2, "Vice President, Sales"},
			                    {3, "Sales Representative"},
			                    {4, "Sales Representative"},
			                    {5, "Sales Manager"},
			                    {6, "Sales Representative"},
			                    {7, "Sales Representative"},
			                    {8, "Sales Representative"},
			                    {9, "Sales Representative"}
			                }
			            ),
			            DATATABLE("anio", INTEGER, {{1996}, {1997}, {1998}})
			        ),
			        DATATABLE("trimestre", INTEGER, {{1}, {2}, {3}, {4}})
			    ),
			    "empleado_id", [empleado_id],
			    "anio",        [anio],
			    "trimestre",   [trimestre],
			    "meta_ventas_usd",
			        IF([title] = "Vice President, Sales", 18000.0,
			        IF([title] = "Sales Manager",         15000.0,
			                                              12000.0)),
			    "categoria_meta",
			        IF([title] = "Vice President, Sales", "Agresiva",
			        IF([title] = "Sales Manager",         "Estándar",
			                                              "Básica"))
			)
			```

	column empleado_id
		dataType: int64
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: empleado_id

	column anio
		dataType: int64
		summarizeBy: none
		sourceColumn: anio

	column trimestre
		dataType: int64
		summarizeBy: none
		sourceColumn: trimestre

	column meta_ventas_usd
		dataType: double
		formatString: "$#,##0.00"
		summarizeBy: sum
		sourceColumn: meta_ventas_usd

	column categoria_meta
		dataType: string
		summarizeBy: none
		sourceColumn: categoria_meta

/// ============================================================
/// TABLA DE HECHOS: fact_ventas
/// Fuente: Orders JOIN Order Details — ~2155 registros
/// Granularidad: 1 fila = 1 línea de detalle de pedido
/// Responde: P1 a P10 (todas las preguntas)
/// ============================================================
table fact_ventas

	partition 'fact_ventas-m' = m
		mode: import
		source = ```
			let
			    Source      = Sql.Database("(localdb)\\MSSQLLocalDB", "Northwind"),
			    Orders      = Source{[Schema="dbo", Item="Orders"]}[Data],
			    OrderDetails= Source{[Schema="dbo", Item="Order Details"]}[Data],
			    OrdSel = Table.SelectColumns(Orders, {
			        "OrderID", "CustomerID", "EmployeeID",
			        "OrderDate", "RequiredDate", "ShippedDate",
			        "ShipVia", "Freight", "ShipCountry", "ShipRegion"
			    }),
			    ODSel = Table.SelectColumns(OrderDetails, {
			        "OrderID", "ProductID", "UnitPrice", "Quantity", "Discount"
			    }),
			    Joined = Table.NestedJoin(
			        ODSel, "OrderID",
			        OrdSel, "OrderID",
			        "OrdData", JoinKind.Inner
			    ),
			    Exp = Table.ExpandTableColumn(Joined, "OrdData", {
			        "CustomerID", "EmployeeID", "OrderDate", "RequiredDate",
			        "ShippedDate", "ShipVia", "Freight", "ShipCountry", "ShipRegion"
			    }),
			    Subtotal    = Table.AddColumn(Exp, "subtotal",
			        each [UnitPrice] * [Quantity], type number),
			    TotalVenta  = Table.AddColumn(Subtotal, "total_venta",
			        each [subtotal] * (1 - [Discount]), type number),
			    CostoUnit   = Table.AddColumn(TotalVenta, "costo_adquisicion_unit",
			        each [UnitPrice] * 0.60, type number),
			    CostoTotal  = Table.AddColumn(CostoUnit, "costo_total",
			        each [costo_adquisicion_unit] * [Quantity], type number),
			    Margen      = Table.AddColumn(CostoTotal, "margen",
			        each [total_venta] - [costo_total], type number),
			    MargenPct   = Table.AddColumn(Margen, "margen_pct",
			        each if [total_venta] = 0 then 0 else [margen] / [total_venta] * 100, type number),
			    DiasEntrega = Table.AddColumn(MargenPct, "dias_entrega",
			        each if [ShippedDate] = null then null
			             else Duration.Days([ShippedDate] - [OrderDate]),
			        type number),
			    EntPuntual  = Table.AddColumn(DiasEntrega, "entrega_puntual",
			        each if [ShippedDate] = null then null
			             else [ShippedDate] <= [RequiredDate],
			        type logical),
			    FechaId     = Table.AddColumn(EntPuntual, "fecha_id",
			        each if [OrderDate] = null then null
			             else Date.ToText([OrderDate], "yyyyMMdd"),
			        type text),
			    FechaEntId  = Table.AddColumn(FechaId, "fecha_entrega_id",
			        each if [ShippedDate] = null then null
			             else Date.ToText([ShippedDate], "yyyyMMdd"),
			        type text),
			    DetailId    = Table.AddColumn(FechaEntId, "order_detail_id",
			        each Text.From([OrderID]) & "-" & Text.From([ProductID]),
			        type text),
			    ShipCntry   = Table.AddColumn(DetailId, "ship_country_safe",
			        each if [ShipCountry] = null then "UNK" else [ShipCountry],
			        type text),
			    ShipReg     = Table.AddColumn(ShipCntry, "ship_region_safe",
			        each if [ShipRegion] = null then "XX" else [ShipRegion],
			        type text),
			    TerrId      = Table.AddColumn(ShipReg, "territorio_id",
			        each Text.Upper(Text.Start([ship_country_safe], 3)) & "-" &
			             Text.Upper(Text.Start([ship_region_safe], 2)),
			        type text),
			    Round2 = Table.TransformColumns(TerrId, {
			        {"subtotal",    each Number.Round(_, 2), type number},
			        {"total_venta", each Number.Round(_, 2), type number},
			        {"costo_total", each Number.Round(_, 2), type number},
			        {"margen",      each Number.Round(_, 2), type number},
			        {"margen_pct",  each Number.Round(_, 2), type number},
			        {"Freight",     each Number.Round(_, 2), type number}
			    }),
			    Final = Table.RenameColumns(Round2, {
			        {"OrderID",     "order_id"},
			        {"CustomerID",  "cliente_id"},
			        {"EmployeeID",  "empleado_id"},
			        {"ProductID",   "producto_id"},
			        {"ShipVia",     "shipper_id"},
			        {"UnitPrice",   "unit_price"},
			        {"Quantity",    "cantidad"},
			        {"Discount",    "descuento"},
			        {"Freight",     "freight"},
			        {"OrderDate",   "order_date"},
			        {"RequiredDate","required_date"},
			        {"ShippedDate", "shipped_date"}
			    }),
			    Columnas = Table.SelectColumns(Final, {
			        "order_detail_id", "order_id",
			        "fecha_id", "fecha_entrega_id",
			        "cliente_id", "empleado_id", "producto_id",
			        "shipper_id", "territorio_id",
			        "cantidad", "unit_price", "descuento", "freight",
			        "subtotal", "total_venta",
			        "costo_total", "margen", "margen_pct",
			        "order_date", "required_date", "shipped_date",
			        "dias_entrega", "entrega_puntual"
			    })
			in
			    Columnas
			```

	column order_detail_id
		dataType: string
		isKey
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: order_detail_id

	column order_id
		dataType: int64
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: order_id

	column fecha_id
		dataType: string
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: fecha_id

	column fecha_entrega_id
		dataType: string
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: fecha_entrega_id

	column cliente_id
		dataType: string
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: cliente_id

	column empleado_id
		dataType: int64
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: empleado_id

	column producto_id
		dataType: int64
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: producto_id

	column shipper_id
		dataType: int64
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: shipper_id

	column territorio_id
		dataType: string
		isHidden
		displayFolder: Claves
		summarizeBy: none
		sourceColumn: territorio_id

	column cantidad
		dataType: int64
		formatString: "#,##0"
		displayFolder: Métricas
		summarizeBy: sum
		sourceColumn: cantidad

	column unit_price
		dataType: double
		formatString: "$#,##0.00"
		displayFolder: Métricas
		summarizeBy: none
		sourceColumn: unit_price

	column descuento
		dataType: double
		formatString: "0.00%"
		displayFolder: Métricas
		summarizeBy: none
		sourceColumn: descuento

	column freight
		dataType: double
		formatString: "$#,##0.00"
		displayFolder: Métricas
		summarizeBy: sum
		sourceColumn: freight

	column subtotal
		dataType: double
		formatString: "$#,##0.00"
		displayFolder: Métricas
		summarizeBy: sum
		sourceColumn: subtotal

	column total_venta
		dataType: double
		formatString: "$#,##0.00"
		displayFolder: Métricas
		summarizeBy: sum
		sourceColumn: total_venta

	column costo_total
		dataType: double
		formatString: "$#,##0.00"
		displayFolder: Métricas
		summarizeBy: sum
		sourceColumn: costo_total

	column margen
		dataType: double
		formatString: "$#,##0.00"
		displayFolder: Métricas
		summarizeBy: sum
		sourceColumn: margen

	column margen_pct
		dataType: double
		formatString: "0.00"
		displayFolder: Métricas
		summarizeBy: none
		sourceColumn: margen_pct

	column order_date
		dataType: dateTime
		formatString: "dd/MM/yyyy"
		displayFolder: Fechas
		summarizeBy: none
		sourceColumn: order_date

	column required_date
		dataType: dateTime
		formatString: "dd/MM/yyyy"
		isHidden
		displayFolder: Fechas
		summarizeBy: none
		sourceColumn: required_date

	column shipped_date
		dataType: dateTime
		formatString: "dd/MM/yyyy"
		displayFolder: Fechas
		summarizeBy: none
		sourceColumn: shipped_date

	column dias_entrega
		dataType: int64
		formatString: "#,##0"
		displayFolder: Métricas
		summarizeBy: none
		sourceColumn: dias_entrega

	column entrega_puntual
		dataType: boolean
		displayFolder: Métricas
		summarizeBy: none
		sourceColumn: entrega_puntual

/// ============================================================
/// TABLA DE MEDIDAS: _Medidas
/// Todas las medidas DAX agrupadas por pregunta de negocio
/// ============================================================
table _Medidas
	isHidden

	partition _Medidas = calculated
		mode: import
		source = ROW("placeholder", "x")

	/// P1 — Ventas por periodo
	measure 'Total Ventas' =
			SUM(fact_ventas[total_venta])
		formatString: "$#,##0.00"
		displayFolder: "P1 Ventas por Periodo"

	measure 'Num Ordenes' =
			DISTINCTCOUNT(fact_ventas[order_id])
		formatString: "#,##0"
		displayFolder: "P1 Ventas por Periodo"

	measure 'Ventas YTD' =
			CALCULATE(
			    [Total Ventas],
			    DATESYTD(dim_fecha[fecha_completa])
			)
		formatString: "$#,##0.00"
		displayFolder: "P1 Ventas por Periodo"

	measure 'Ventas Año Anterior' =
			CALCULATE(
			    [Total Ventas],
			    SAMEPERIODLASTYEAR(dim_fecha[fecha_completa])
			)
		formatString: "$#,##0.00"
		displayFolder: "P1 Ventas por Periodo"

	measure 'Variación YoY %' =
			VAR VentasActual  = [Total Ventas]
			VAR VentasAnterior = [Ventas Año Anterior]
			RETURN
			    IF(
			        ISBLANK(VentasAnterior) || VentasAnterior = 0,
			        BLANK(),
			        DIVIDE(VentasActual - VentasAnterior, VentasAnterior) * 100
			    )
		formatString: "0.00"
		displayFolder: "P1 Ventas por Periodo"

	/// P2 — Clientes rentables
	measure 'Clientes Activos' =
			DISTINCTCOUNT(fact_ventas[cliente_id])
		formatString: "#,##0"
		displayFolder: "P2 Clientes Rentables"

	measure 'Ventas por Cliente' =
			DIVIDE([Total Ventas], [Clientes Activos], 0)
		formatString: "$#,##0.00"
		displayFolder: "P2 Clientes Rentables"

	measure 'Ranking Cliente' =
			RANKX(
			    ALL(dim_cliente[company_name]),
			    [Total Ventas],
			    ,
			    DESC,
			    DENSE
			)
		formatString: "#,##0"
		displayFolder: "P2 Clientes Rentables"

	/// P3 — Productos más vendidos
	measure 'Unidades Vendidas' =
			SUM(fact_ventas[cantidad])
		formatString: "#,##0"
		displayFolder: "P3 Productos Vendidos"

	measure '% Contribución Ventas' =
			DIVIDE(
			    [Total Ventas],
			    CALCULATE([Total Ventas], ALL(dim_producto)),
			    0
			) * 100
		formatString: "0.00"
		displayFolder: "P3 Productos Vendidos"

	/// P4 — Análisis por categorías
	measure 'Ventas por Categoría' =
			CALCULATE(
			    [Total Ventas],
			    ALLEXCEPT(dim_producto, dim_producto[categoria])
			)
		formatString: "$#,##0.00"
		displayFolder: "P4 Categorías"

	/// P5 — Eficiencia de empleados
	measure 'Meta Periodo' =
			SUMX(
			    FILTER(
			        dim_metas_empleado,
			        dim_metas_empleado[empleado_id] = SELECTEDVALUE(dim_empleado[empleado_id])
			        && dim_metas_empleado[anio]     = SELECTEDVALUE(dim_fecha[anio])
			        && dim_metas_empleado[trimestre] = SELECTEDVALUE(dim_fecha[trimestre])
			    ),
			    dim_metas_empleado[meta_ventas_usd]
			)
		formatString: "$#,##0.00"
		displayFolder: "P5 Eficiencia Empleados"

	measure '% Cumplimiento Meta' =
			DIVIDE([Total Ventas], [Meta Periodo], 0) * 100
		formatString: "0.00"
		displayFolder: "P5 Eficiencia Empleados"

	measure 'Ranking Empleado' =
			RANKX(
			    ALL(dim_empleado[full_name]),
			    [Total Ventas],
			    ,
			    DESC,
			    DENSE
			)
		formatString: "#,##0"
		displayFolder: "P5 Eficiencia Empleados"

	/// P6 — Análisis de territorios
	measure 'Ventas por País' =
			CALCULATE(
			    [Total Ventas],
			    ALLEXCEPT(dim_territorio, dim_territorio[country])
			)
		formatString: "$#,##0.00"
		displayFolder: "P6 Territorios"

	measure '% Contribución Territorial' =
			DIVIDE(
			    [Total Ventas],
			    CALCULATE([Total Ventas], ALL(dim_territorio)),
			    0
			) * 100
		formatString: "0.00"
		displayFolder: "P6 Territorios"

	/// P7 — Tiempos de entrega
	measure 'Avg Dias Entrega' =
			AVERAGEX(
			    FILTER(
			        fact_ventas,
			        NOT ISBLANK(fact_ventas[dias_entrega])
			        && fact_ventas[dias_entrega] >= 0
			    ),
			    fact_ventas[dias_entrega]
			)
		formatString: "0.0"
		displayFolder: "P7 Tiempos Entrega"

	measure 'Pedidos Entregados' =
			COUNTROWS(
			    FILTER(fact_ventas, NOT ISBLANK(fact_ventas[shipped_date]))
			)
		formatString: "#,##0"
		displayFolder: "P7 Tiempos Entrega"

	measure 'Pedidos Pendientes' =
			COUNTROWS(
			    FILTER(fact_ventas, ISBLANK(fact_ventas[shipped_date]))
			)
		formatString: "#,##0"
		displayFolder: "P7 Tiempos Entrega"

	measure '% Entregas Puntuales' =
			VAR Puntuales =
			    COUNTROWS(
			        FILTER(
			            fact_ventas,
			            fact_ventas[entrega_puntual] = TRUE()
			        )
			    )
			VAR Entregados = [Pedidos Entregados]
			RETURN
			    DIVIDE(Puntuales, Entregados, 0) * 100
		formatString: "0.0"
		displayFolder: "P7 Tiempos Entrega"

	/// P8 — Margen de rentabilidad
	measure 'Total Margen' =
			SUM(fact_ventas[margen])
		formatString: "$#,##0.00"
		displayFolder: "P8 Margen Rentabilidad"

	measure 'Total Costo' =
			SUM(fact_ventas[costo_total])
		formatString: "$#,##0.00"
		displayFolder: "P8 Margen Rentabilidad"

	measure '% Margen Promedio' =
			DIVIDE([Total Margen], [Total Ventas], 0) * 100
		formatString: "0.00"
		displayFolder: "P8 Margen Rentabilidad"

	measure 'Ranking Margen Producto' =
			RANKX(
			    ALL(dim_producto[product_name]),
			    [Total Margen],
			    ,
			    DESC,
			    DENSE
			)
		formatString: "#,##0"
		displayFolder: "P8 Margen Rentabilidad"

	/// P9 — Clientes inactivos
	measure 'Última Compra Cliente' =
			CALCULATE(
			    MAX(fact_ventas[order_date]),
			    ALLEXCEPT(dim_cliente, dim_cliente[cliente_id])
			)
		formatString: "dd/MM/yyyy"
		displayFolder: "P9 Clientes Inactivos"

	measure 'Días Sin Comprar' =
			VAR UltimaFecha = [Última Compra Cliente]
			VAR FechaMax    = CALCULATE(MAX(fact_ventas[order_date]), ALL(fact_ventas))
			RETURN
			    IF(
			        ISBLANK(UltimaFecha),
			        BLANK(),
			        DATEDIFF(UltimaFecha, FechaMax, DAY)
			    )
		formatString: "#,##0"
		displayFolder: "P9 Clientes Inactivos"

	measure 'Es Cliente Inactivo' =
			IF([Días Sin Comprar] > 365, "Inactivo", "Activo")
		displayFolder: "P9 Clientes Inactivos"

	/// P10 — Estacionalidad
	measure 'Ventas por Trimestre' =
			CALCULATE(
			    [Total Ventas],
			    ALLEXCEPT(dim_fecha, dim_fecha[anio], dim_fecha[trimestre])
			)
		formatString: "$#,##0.00"
		displayFolder: "P10 Estacionalidad"

	measure 'Variación vs Trimestre Anterior' =
			VAR VentasActual = [Total Ventas]
			VAR VentasAnterior =
			    CALCULATE(
			        [Total Ventas],
			        DATEADD(dim_fecha[fecha_completa], -1, QUARTER)
			    )
			RETURN
			    DIVIDE(VentasActual - VentasAnterior, VentasAnterior, BLANK()) * 100
		formatString: "0.00"
		displayFolder: "P10 Estacionalidad"

	measure 'Índice Estacionalidad' =
			VAR VentasTrimestre = [Total Ventas]
			VAR VentasPromTrimestre =
			    AVERAGEX(
			        ALL(dim_fecha[trimestre]),
			        CALCULATE([Total Ventas])
			    )
			RETURN
			    DIVIDE(VentasTrimestre, VentasPromTrimestre, 0)
		formatString: "0.00"
		displayFolder: "P10 Estacionalidad"

relationship 'fv_fecha'
	fromColumn: fact_ventas.fecha_id
	toColumn: dim_fecha.fecha_id

relationship 'fv_fecha_entrega'
	fromColumn: fact_ventas.fecha_entrega_id
	toColumn: dim_fecha.fecha_id
	isActive: false

relationship 'fv_cliente'
	fromColumn: fact_ventas.cliente_id
	toColumn: dim_cliente.cliente_id

relationship 'fv_empleado'
	fromColumn: fact_ventas.empleado_id
	toColumn: dim_empleado.empleado_id

relationship 'fv_producto'
	fromColumn: fact_ventas.producto_id
	toColumn: dim_producto.producto_id

relationship 'fv_shipper'
	fromColumn: fact_ventas.shipper_id
	toColumn: dim_shipper.shipper_id

relationship 'fv_territorio'
	fromColumn: fact_ventas.territorio_id
	toColumn: dim_territorio.territorio_id

annotation __PBI_TimeIntelligenceEnabled = 1
annotation PBI_ProTooling = ["DevMode"]

ref cultureInfo es-CO

